### PR TITLE
Add dependency info to setup.py

### PR DESCRIPTION
**Pull request by cslycord**
Added install_requires information into setuptools section so that the package can track dependencies properly.

### CODE REVIEW

**Comment by riverrun** [comment]
Thanks for the help.

By the way, what will happen if the dependencies, outlined by 'install_requires' are not present? Will it just present a warning to the user?

**Comment by cslycord** [comment]
If you're using pip for installation and don't manually install pycairo
and PyGObject, then genxword installs fine, but crashes when run.

genxword displays ModuleNotFoundError: No module named 'gi'

There's no warning at installation, because pip didn't know what to warn
you about. And there's no warning upon it being run, because the script
imports without checking.

**Comment by riverrun** [comment]
Ok. So does 'install_requires' work as a form of documentation then (telling the user what is needed)?

**Comment by cslycord** [comment]
No. It's for making the package itself aware of its own dependencies so
that running "pip install genxword" automatically installs the packages
mentioned in install_requires.

**Pull request merged**
